Controllers/AcademicController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SMS.Models;
using System.Text;
using System.Xml;

namespace SMS.Controllers
{
    public class AcademicController : Controller
    {
        HttpClient client;

        public AcademicController()
        {
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            client = new HttpClient(clientHandler);
        }


        public IActionResult Index()
        {
            List<Curriculum> curricula = new List<Curriculum>();
            string url = "https://localhost:44386/api/Academic/GetAllCurricula";
            HttpResponseMessage response = client.GetAsync(url).Result;

            if (response.IsSuccessStatusCode)
            {
                var jsondata = response.Content.ReadAsStringAsync().Result;
                curricula = JsonConvert.DeserializeObject<List<Curriculum>>(jsondata);
            }

            return View(curricula);
        }


        public IActionResult AddCurriculum()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCurriculum(Curriculum curriculum)
        {
            string url = "https://localhost:44386/api/Academic/AddCurriculum";
            var jsonData = JsonConvert.SerializeObject(curriculum);
            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View(curriculum);
        }
        public IActionResult AddTimetable()
        {
            return View();

        }
        [HttpPost]
        public IActionResult AddTimetable(TimeTable tt)
        {
            string url = "https://localhost:44386/api/Academic/AddTimeTable";
            var jsondata = JsonConvert.SerializeObject(tt);
            StringContent content = new StringContent(jsondata, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["Msg"] = "TimeTable Added Successfully";
                return RedirectToAction("AddTimetable");
            }
            else
            {
                TempData["Msg"] = "Couldn't add Timetable please try again";
                return View();
            }
        }
        public IActionResult GetTimeTable()
        {

            List<TimeTable> teach = new List<TimeTable>();

            string url = "https://localhost:44386/api/Academic/GetTimeTable";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                var jsondata = response.Content.ReadAsStringAsync().Result;
                teach = JsonConvert.DeserializeObject<List<TimeTable>>(jsondata);
            }
            return View(teach);
        }
        public IActionResult AddSubjects()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSubjects(Subject sub)
        {
            string url = "https://localhost:44386/api/Academic/AddSub";
            var jsondata = JsonConvert.SerializeObject(sub);
            StringContent stringContent = new StringContent(jsondata, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(url, stringContent).Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["Msg"] = "Subject Added Succesfully";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Msg"] = "Something Went Wrong Please Try Again Later";
                return View();

            }
        }
        public IActionResult FetchSubjects()
        {
            List<Subject> sub = new List<Subject>();
            string url = "https://localhost:44386/api/Academic/GetSub";
            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                var jsondata = response.Content.ReadAsStringAsync().Result;
                sub = JsonConvert.DeserializeObject<List<Subject>>(jsondata);
                return Json(sub);
            }
            else
            {
                return Json(null);
            }
        }

    }
}

Views/Academic/AddCurriculum.cshtml
@model Curriculum

@{
    ViewData["Title"] = "Add Curriculum";
}

<h2>Add Curriculum</h2>

<form asp-action="AddCurriculum" method="post">
    <div class="form-group">
        <label asp-for="CourseName" class="control-label">Course Name</label>
        <input asp-for="CourseName" class="form-control" />
        
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label">Description</label>
        <textarea asp-for="Description" class="form-control"></textarea>
      
    </div>

    <div class="form-group">
        <label asp-for="Syllabus" class="control-label">Syllabus</label>
        <textarea asp-for="Syllabus" class="form-control"></textarea>
        
    </div>

    <div class="form-group">
        <input type="submit" value="Add Curriculum" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Academic/AddSubjects.cshtml
@model Subject
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title fw-semibold mb-4">Forms</h5>
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        <div class="mb-3">
                            <label class="form-label">Subject Name</label>
                            <input type="text" class="form-control" asp-for="SubjectName">
                        </div>
                       

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <div class="py-6 px-6 text-center">
    </div>
</div>

Views/Academic/AddTimeTable.cshtml
@model TimeTable



<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title fw-semibold mb-4">Forms</h5>
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        <div class="mb-3">
                            <label class="form-label">Select Class</label>
                            <select class="form-control" asp-for="ClassId" id="FetchAllClasses">
                               
                            </select>
                                

                        </div>
                        <div class="mb-3">
                            <label class="form-label">Select Day</label>
                            <select class="form-control" asp-for="Day">
                                <option value="Monday">Monday</option>
                                <option value="Tuesday">Tuesday</option>
                                <option value="Wednesday">Wednesday</option>
                                <option value="Thursday">Thursday</option>
                                <option value="Friday">Friday</option>
                            </select>

                        </div>
                        <div class="mb-3">
                            <label class="form-label">Select Start Time</label>
                            <select class="form-control" asp-for="StartTime">
                                <option value="09:00">09:00 </option>
                                
                                <option value="10:00">10:00 </option>
                                
                                <option value="11:00">11:00 </option>
                                
                                <option value="12:00">12:00 </option>
                                
                                <option value="13:00">13:00 </option>
                                
                                <option value="14:00">14:00 </option>
                                
                                <option value="15:00">15:00 </option>
                               
                                <option value="16:00">16:00 </option>
                                
                                <option value="17:00">17:00 </option>
                                
                                <option value="18:00">18:00 </option>  
                            </select>

                        </div>
                        <div class="mb-3">
                            <label class="form-label">Select End Time</label>
                            <select class="form-control" asp-for="EndTime">
                                <option value="09:00">09:00 </option>

                                <option value="10:00">10:00 </option>

                                <option value="11:00">11:00 </option>

                                <option value="12:00">12:00 </option>

                                <option value="13:00">13:00 </option>

                                <option value="14:00">14:00 </option>

                                <option value="15:00">15:00 </option>

                                <option value="16:00">16:00 </option>

                                <option value="17:00">17:00 </option>

                                <option value="18:00">18:00 </option>
                                @*  <option value="09:30">09:30 </option>
                                
                                <option value="10:30">10:30 </option>
                                
                                <option value="11:30">11:30 </option>
                               
                                <option value="12:30">12:30 </option>
                                
                                <option value="13:30">13:30 </option>
                                
                                <option value="14:30">14:30 </option>
                                
                                <option value="15:30">15:30 </option>
                                
                                <option value="16:30">16:30 </option>
                                
                                <option value="17:30">17:30 </option>
                                <option value="18:00">18:30 </option> *@
                            </select>

                        </div>
                        <div class="mb-3">
                            <label class="form-label">Select Subject</label>
                            <select class="form-control" id="GetSubjects" asp-for="Subject">
                                <option value="10:00">Maths </option>

                                <option value="11:00">English </option>

                                <option value="12:00">History</option>

                                <option value="13:00">Physics </option>

                                <option value="14:00">Hindi </option>
                            </select>

                        </div>
                        
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Select Teacher Coordinator</label>
                            <select class="form-control" id="FetchTeacherData" asp-for="TeacherId">
                                <option>select teacher</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <div class="py-6 px-6 text-center">
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/ajax/javascript.js"></script>

Views/Academic/FetchSubjects.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Academic/GetTimetable.cshtml
@using ﻿SMSWEBAPI.Models
@model List<TimeTable>
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly Schedule</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/assets/css/stylesheet.css" rel="stylesheet" />
</head>
<body>

    <header class="text-center my-5">
        <h1 class="display-5">Weekly Schedule</h1>
    </header>

    <div class="container timetable">
        <!-- Time Column -->
        @for (int hour = 9; hour <= 18; hour++)
        {
            <div class="time-column">@hour:00</div>
        }

        <!-- Day Headers -->
        <div class="day-header">Monday</div>
        <div class="day-header">Tuesday</div>
        <div class="day-header">Wednesday</div>
        <div class="day-header">Thursday</div>
        <div class="day-header">Friday</div>

        <!-- Events -->
        @foreach (var item in Model)
        {
            var gridColumn = item.Day switch
            {
                "Monday" => 2,
                "Tuesday" => 3,
                "Wednesday" => 4,
                "Thursday" => 5,
                "Friday" => 6,
                _ => 0
            };

            var startHour = DateTime.Parse(item.StartTime).Hour - 8;
            var endHour = DateTime.Parse(item.EndTime).Hour - 8; 

            <div class="event" style="grid-column: @gridColumn; grid-row: @startHour / @endHour;">
                @item.StartTime - @item.EndTime<br>@item.Subject - @item.TeacherId
            </div>
        }
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Academic/Index.cshtml
@model List<Curriculum>

@{
    ViewData["Title"] = "Curriculum List";
}
<a asp-controller="Academic" asp-action="AddCurriculum"><input type="button" value="Add Student" class=" btn btn-primary" /></a>
<h2>Curriculum List</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Course Name</th>
            <th>Description</th>
            <th>Syllabus</th>
        </tr>
    </thead>
    <tbody>
       
            
          @foreach(var curriculum in Model)
            {
                <tr>
                    <td>@curriculum.CurriculumId</td>
                    <td>@curriculum.CourseName</td>
                    <td>@curriculum.Description</td>
                    <td>@curriculum.Syllabus</td>
                </tr> 
            }
        
        
    </tbody>
</table>